micronaut:
  application:
    name: m4configuratio
netty:
  default:
    allocator:
      max-order: 3

hello:
  world:
    rate: 10m

onstructive:
  product-engine:
    insurance-needs:
      insurance-needs:
        - key: insuranceNeeds.best.price
          id: bc14def2-07f9-4790-a5ba-4cea80d51d35
          products:
            - name: PRD_GV_BTC
            - name: PRD_ZV_SP3
            - name: PRD_KA_UTI
            - name: PRD_KA_KTI
              constraint:
                type: AGE
                range: "0..14"

    product-configuration:
      default-base-insurance-product: PRD_GV_BTC # Telmed
      third-kid-discount-code-active: COD_RK_BER
      third-kid-discount-code-inactive: COD_RK_NBE
      family-discount-code-active: COD_RK_MRA
      family-discount-code-inactive: COD_RK_ORA
      products:
        - name: PRD_KA_KTI # KTI
          insurance-begin-strategy: FIRST_DAY_OF_THE_FOLLOWING_YEAR_OR_NEXT_MONTH
          constraint:
            type: AGE
            range: "0..54"
          legal-basis: VVG
          criteria:
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "0..0"
              value: COD_LA_B01
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "1..3"
              value: COD_LA_B03
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "4..14"
              value: COD_LA_B04
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "15..18"
              value: COD_LA_B15
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "19..20"
              value: COD_LA_B19
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "21..25"
              value: COD_LA_B21
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "26..30"
              value: COD_LA_B26
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "31..35"
              value: COD_LA_B31
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "36..40"
              value: COD_LA_B36
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "41..45"
              value: COD_LA_B41
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "46..50"
              value: COD_LA_B46
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "51..55"
              value: COD_LA_B51
            - name: SEX
              exposable: false
              constraint:
                type: SEX
                value: "MALE"
              value: COD_GS_MAN
            - name: SEX
              exposable: false
              constraint:
                type: SEX
                value: "FEMALE"
              value: COD_GS_WEI
            - name: INSURANCE_SUM_DEATH
              exposable: true
              constraint:
                type: AGE
                range: "0..3"
              value: COD_VS_T01 # 2'500
            - name: INSURANCE_SUM_DEATH
              exposable: true
              constraint:
                type: AGE
                range: "4..14"
              value: COD_VS_T02 # 10'000
            - name: INSURANCE_SUM_DEATH
              exposable: true
              constraint:
                type: AGE
                range: "15..55"
              value: COD_VS_T04 # 10'000
            - name: INSURANCE_SUM_INVALIDITY
              exposable: true
              constraint:
                type: AGE
                range: "0..55"
              value: COD_VS_I10 # 100'000
            - name: ACCIDENT
              exposable: true
              constraint:
                type: AGE
                range: "0..55"
              value: COD_UZ_AUS # Since we propose UTI
